plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.juuxel.loom-quiltflower' version '1.8.0'
    id 'mod-update' version '2.0.0'
    id "com.github.breadmoirai.github-release" version "2.4.1"
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = archives_base_name
version = mod_version
group = maven_group
/*
loom {
    accessWidenerPath = file('src/main/resources/audioplayer.accesswidener')
}*/

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.maxhenkel.de/repository/public' }
    maven { url = "https://maven.kosmx.dev" }
    maven {
        url = 'https://api.modrinth.com/maven'
    }
    maven {
         name = 'ParchmentMC'
         url = 'https://maven.parchmentmc.org'
     }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
    modImplementation "maven.modrinth:simple-voice-chat:fabric-${project.voicechat_mod_version}"

    modImplementation "io.github.kosmx.emotes:emotesMain:${project.emotecraft}"
    modImplementation "dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_animation_lib}"
    modImplementation "maven.modrinth:emotecraft:${project.emotecraft}+${project.minecraft_version}-fabric"
}

processResources {
    inputs.property "version", version
    filteringCharset "UTF-8"

    filesMatching('fabric.mod.json') {
        expand 'version': version,
                'minecraft_dependency': minecraft_dependency,
                'minecraft_version': minecraft_version,
                'loader_version': loader_version,
                'fabric_version': fabric_version,
                'voicechat_api_version': voicechat_api_version,
                'emotecraft': emotecraft
    }
}

def targetJavaVersion = 17
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release = targetJavaVersion
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    archivesBaseName = project.archives_base_name

    withSourcesJar()
}

jar {
    from('LICENSE') {
        rename { "${it}_${archivesBaseName}+${version}" }
    }
}
/*
curseforge {
    apiKey = file('curseforge_api_key.txt').exists() ? file('curseforge_api_key.txt').text : ''
    project {
        id = curse_id
        changelogType = 'markdown'
        changelog = file('changelog.md')
        releaseType = release_type
        addGameVersion curseforge_minecraft_version
        addGameVersion 'Fabric'
        addGameVersion 'Java 17'
        mainArtifact(file("${buildDir}/libs/${archivesBaseName}-${version}.jar")) {
            displayName = "[FABRIC][${minecraft_version}] ${mod_name} ${mod_version}"
            relations {
                requiredDependency 'fabric-api'
                requiredDependency 'simple-voice-chat'
            }
        }
        afterEvaluate {
            uploadTask.dependsOn(remapJar)
        }
    }
    options {
        forgeGradleIntegration = false
    }
}

tasks.modrinth.configure({
    group = 'upload'
})
tasks.modrinthSyncBody.configure({
    group = 'upload'
})

modrinth {
    token = file("${rootDir}/modrinth_token.txt").exists() ? file("${rootDir}/modrinth_token.txt").text : ''
    projectId = modrinth_id
    versionNumber = "fabric-${mod_version}"
    versionName = "[FABRIC][${minecraft_version}] ${mod_name} ${mod_version}"
    uploadFile = remapJar
    versionType = release_type.toUpperCase()
    changelog = file('changelog.md').text
    gameVersions = [minecraft_version]
    loaders = ['fabric']
    syncBodyFrom = file('readme.md').text
    dependencies {
        required.project 'P7dR8mSH' // Fabric API
        required.project '9eGKb6K1' // Simple Voice Chat
    }
}
tasks.modrinth.dependsOn(build)

modUpdate {
    serverURL = 'n/a'
    modID = mod_id
    gameVersion = minecraft_version
    modLoader = 'fabric'
    modVersion = mod_version
    changelogFile = file('changelog.md')
    releaseType = release_type
    tags = recommended == 'true' ? ['recommended'] : []
}

shadowJar {
    configurations = [project.configurations.shadow]
    archiveClassifier = 'shadow-dev'
    relocate 'de.maxhenkel.configbuilder', "de.maxhenkel.${mod_id}.configbuilder"
    relocate 'javazoom', "de.maxhenkel.${mod_id}.javazoom"
    relocate 'org.tritonus', "de.maxhenkel.${mod_id}.tritonus"
}

remapJar {
    dependsOn shadowJar
    inputFile = shadowJar.archiveFile.get()
}*/